# Site settings
author: atracta
title: All about the code....
header-img: img/home-bg.png
email: kazzim@icloud.com
copyright_name: atracta
description: > # this means to ignore newlines until "baseurl:"
  ....and then some
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ninadecoder

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
